# Generated by Django 3.1.1 on 2020-09-13 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treechart', '0002_chart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
