# Generated by Django 3.1.1 on 2020-09-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptt_graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treenode',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='treenode',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='treenode',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
